# Generated by Django 4.1.3 on 2022-12-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_postal_codes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="county",
            options={"ordering": ["district", "name"]},
        ),
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ["country", "name"]},
        ),
        migrations.AlterModelOptions(
            name="locality",
            options={"ordering": ["county", "name"]},
        ),
        migrations.AlterModelOptions(
            name="postalcode",
            options={
                "ordering": ["locality", "full_address"],
                "verbose_name": "Postal Code",
                "verbose_name_plural": "Postal Codes",
            },
        ),
    ]
