# Generated by Django 4.1.8 on 2023-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_postal_codes",
            "0002_alter_country_options_alter_county_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="county",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="locality",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="artery_local",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Artery local"
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="artery_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Artery name"
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="artery_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Artery title"
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="artery_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Artery type"
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="prep1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="prep 1"
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="prep2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="prep 2"
            ),
        ),
    ]
